### PR TITLE
Chapter 2 and 3

### PR DESCRIPTION
**Pull request by Jumeb**

### CODE REVIEW

**Comment by Jumeb** [comment]
Mentor good afternoon, I have tried to download the eloquent JavaScript
sandbox book but the page gives me a "404 Not Found" error
So should I continue without the sandbox book??
Here us the link "eloquentjavascript.net/code"

**Comment by kengneruphine** [comment]
Hello

Why do you need a sandbox book for???

**Comment by Jumeb** [comment]
Mentor I don't understand the problem on Historical life Expectancy in
Chapter 5 and the ones that follow. But I have done the exercise above it
and submitted.
I'll be heading on to chapter 6 until you get back tome on what to do
Thanks for understanding

**Comment by Jumeb** [comment]
Sorry for taking too long before pushing my next code

**Comment by Jumeb** [comment]
Mentor good afternoon, I know your are very busy, but I won't lie you,
Chapter 6 is not moving, and there are some files that I have to download
from the website but I can't find them.
I was wondering  because I saw the recent version of Eloquent JavaScript
the third edition released this January, could I use that one instead

**Comment by Jumeb** [comment]
Here is a copy of the book

**Pull request merged**
